# Generated by Django 3.1 on 2020-08-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='personal_key',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
    ]
