# Generated by Django 3.1 on 2020-08-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_personal_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='personal_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
