# Generated by Django 3.1 on 2020-08-18 09:06

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_order_original_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='city', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(default='az', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='234', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(default='123', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(default='123', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='street_address1',
            field=models.CharField(default='312', max_length=80),
            preserve_default=False,
        ),
    ]
