# Generated by Django 3.1 on 2020-08-14 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_remove_order_booking'),
        ('bookings', '0002_auto_20200814_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='checkout.order'),
        ),
    ]
