# Generated by Django 3.1 on 2020-08-14 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_number',
        ),
    ]
