# Generated by Django 3.1 on 2020-08-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discontinued',
            field=models.BooleanField(default=False),
        ),
    ]
